
dependencies:
  - 'Openzeppelin/openzeppelin-contracts@4.3.0'
  - 'smartcontractkit/chainlink-brownie-contracts@0.2.1'

compiler:
  solc:
    remappings:
      - '@openzeppelin=Openzeppelin/openzeppelin-contracts@4.3.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'

wallets:
 from_key: ${PRIVATE_KEY}

dotenv: .env

networks:
  development:
    verify: False
  ganache-local:
   verify: False
  kovan:
    verify: True
  bsc_test:
    verify: false
  bsc_mainnet:
    verify: False
  ganache:
    verify: False
